#!/bin/bash

################################################################
# @Author:      Paolo Stivanin aka Polslinux		       
# @Name:        Bash Password Manager Install Script		                      
# @Copyright:   2011					       
# @Site:        http://www.polslinux.it                          
# @License:     GNU GPL v3 http://www.gnu.org/licenses/gpl.html  
################################################################

distro=$(cat /etc/issue | cut -d' ' -f1 -s)

echo -ne "* Checking user's privileges...\n"
if [ "$(id -u)" != "0" ]; then 
	echo "	ERROR: User $(whoami) is not root, and does not have sudo privileges"
	if [ "$distro" == "Debian" ] ; then echo "        Type su in the terminal and re-run this script"
	elif [ "$distro" == "Ubuntu" ] ; then echo "        Type sudo su in the terminal and re-run this script"
	elif [ "$distro" == "Arch" ] ; then echo "        Type su in the terminal and re-run this script"
	fi
	exit 1
else
	echo "   Write your exact username:"
	read username
fi

echo -ne "* Checking type of your linux distros...\n"
if [ "$distro" == "Debian" ] || [ "$distro" == "Ubuntu" ] || [ "$distro" == "Arch" ];then
	echo "   Ok, you're running $distro and Bash Password Manager is compatible with it!"
else
	echo  "   WARNING: Bash Password Manager is tested to work with Debian, Ubuntu and Archlinux,"
	echo  "   try it on your system and tell me if there is something wrong!"
fi

echo "* Checking deps..."
pkg1=`which zenity`
if [ $? == 0 ] ; then
pkg1_ver=`zenity --version | sed 's/[^0-9]*//g'`
 if [ $pkg1_ver -lt 315 ] ; then
   echo "ERROR: Zenity version MUST be > 3.1.5"
   exit 1
 fi
elif [ $? != 0 ] ; then
echo "--> ERROR: You have to install zenity before continue..."
exit 1
fi
pkg2=`which bash`
if [ $? != 0 ] ; then
echo "--> ERROR: You have to install bash before continue..."
exit 1
fi
pkg3=`which gpg`
if [ $? != 0 ] ; then
echo "--> ERROR: You have to install gpg before continue..."
exit 1
fi
pkg4=`which pinentry-gtk-2`
if [ $? != 0 ] ; then
echo "--> ERROR: You have to install pinentry-gtk2 before continue..."
exit 1
fi
echo -ne"OK!\n"

echo "* Installing files..."
if [ ! -d /usr/share/doc/bash-pwd-manager ] ; then
	mkdir /usr/share/doc/bash-pwd-manager
fi
cp LICENSE README uninstall docs/* /usr/share/doc/bash-pwd-manager
cp bin/bashpwdm /usr/local/bin
cp bin/bashpwdm-config /usr/local/bin
#cp docs/bashpwdm.desktop /usr/share/applications/
#cp docs/bpwdm.png /usr/share/pixmaps/
chown $username /usr/local/bin/bashpwdm
chown $username /usr/local/bin/bashpwdm-config
chmod +x /usr/local/bin/bashpwdm
chmod +x /usr/local/bin/bashpwdm-config
echo -ne "OK!\n"
exit 0
